### ISSUE TITLE
Make repository private

### ISSUE THREAD

**Issue by thinksilicon** [masukomi/masuconfigs#1]
Hi,
sorry for reaching out so blatantly, but you should really consider making this repository private. I don't think your peers in 
https://github.com/masukomi/masuconfigs/blob/master/.config/neomutt/aliases
are very happy that everybody can see their name + e-mail now.

Also you uploaded part of your INBOX
https://github.com/masukomi/masuconfigs/tree/master/.config/neomutt/bodies/imaps_masukomi_gmail.com_imap.gmail.com_993/INBOX

let alone your username and password, free for everyone to access:
set imap_user = "masukomi@gmail.com"
set imap_pass = "xluxmvuiizdlzjao"

**Comment by masukomi** [comment]
Sorry i didn't notice this earlier. didn't expect anyone to file an issue against this repo.

Thank you for pointing that out @thinksilicon  It was an accidental commit that shouldn't have been made. Passwords have since been changed and are now accessed via the `security` app or encrypted. 

i think there's a fair amount of value in having the repo public. Just need to be more vigilant about committing things like that.
